--liquibase formatted sql

-- changeset yourname:001_create_tables

create table if not exists department (
      id  bigint primary key generated by default as identity,
      "name" varchar(255) not null
);

create table if not exists employee (
     id  bigint primary key generated by default as identity,
     "name" varchar(255) not null,
     "position" varchar(255) not null,
     department_id bigint not null,

     foreign key (department_id) references department(id) on delete set null
);

-- rollback drop table pet_tags, tag, pet, category;